In [13]:
z = np.zeros((3, 4))
print z

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [ ]:
# the number of words in document d that have topic allocation k
def n_dk(corpus, z, K):   
    n_dk = np.zeros((corpus.N, K))
    
    for k in range(K):
        for d in range(corpus.N):
            n_dk[d,k]= sum(np.equal(z[d] ,k+1))

    return n_dk


# mk,v be the number of times topic k allocation variables generate term 
# def m_kv(corpus, , ):
    # Blablabla
    

In [ ]:
import numpy as np
import scipy as sp
from scipy.special import gammaln

N = len(corpus.corpus_tokens) # number of unique words
D = corpus.N                  # number of documents
K = 3                         # number of topics
alpha = 1                     # hyperparameter 1
eta = 1                       # hyperparameter 2

S = 5                         # number of iterations
burn_in = 2                   # burn in period
z = np.random.randint()       # Randomly allocate the topics list inside a list 
theta = 
beta = 


 
for s in range(S):
    
    n_dk = n_dk(corpus, z, K)
    
    for d in range(D): 
        # Sample:
        # multinomial distribution N times for the topic allocation variables
        np.random.multinomial(N,?)
        
        # Dirichlet D times for the document-specific mixing probabilities. 
        # Draw βk independently for k = 1, . . . , K from Dirichlet(η).
        beta = np.random.dirichlet([]*D, ?)
        # Dirichlet K times for the topic-specific term probabilities
        
        # Sample from a Dirichlet K times for the topic-specific term probabilities
        # Conditional distribution of θd given zd
        theta_d = np.random.dirichlet([alpha]*K + n_dk[d, ], 1)
        
    
    
    if s <= burn_in:
        next
    
    # else, collect the samples. 
        
    
# Use collected samples to approximate joint distributions.
