In [27]:
z = np.zeros((3, 4))
z[1,:] = [1,2,3,4]
print z

[[ 0.  0.  0.  0.]
 [ 1.  2.  3.  4.]
 [ 0.  0.  0.  0.]]


In [ ]:
import numpy as np

# the number of words in document d that have topic allocation k
def n_k(corpus, z, K):      
    n_k = [[sum(np.equal(z ,k+1))] for k in range(K)]
    return n_k


# for each word, the number of times each topic appears
def m_k(corpus, Z, K): 
    m_k = [[sum(np.equal(Z ,k+1))] for k in range(K)]
    return m_k


In [ ]:

#import scipy as sp


N = len(corpus.corpus_tokens) # number of unique words
D = corpus.N                  # number of documents
K = 3                         # number of topics
alpha = 1                     # hyperparameter 1
eta = 1                       # hyperparameter 2

S = 5                         # number of iterations
burn_in = 2                   # burn in period


Z = np.random.randint(K)  # Randomly allocate the topics list inside a list 

# beta = matrix # % of topic in a word (given a document)
# theta = matrix col = topics # % of topic in a document 

 
for s in range(S):
    for d in range(D): 
        
        # Allocate
        # 1. Comput probs
        # 2. sample from a multinomial distribution N times for the topic allocation variables
        
        V = len(corpus.docs[d].tokens)
        z = []
        
        for v in range(V):
            all_prob = [[theta[d,k] * beta[v,k] / np.dot(theta[d,],beta[,v])] for k in (range(K)+1)]
            z[v] = np.argmax( np.random.multinomial(1, all_prob, 1) )
            
        # Sample from a Dirichlet K times for the topic-specific term probabilities
        n_k = n_k(corpus, z, K)
        theta_cprobs = np.random.dirichlet([alpha]*K + n_dk, 1)
        theta[d] = np.random.dirichlet(theta_cprobs, 1)
        
     
    for v in range(N):
        v_token = corpus.self_tokens[v]
        
        Z_v = [[Z[d][np.equal(corpus.docs[d].tokens, v_token)]] for d in range(D)]
        m_k = m_k(corpus, Z_v, K)
        
        # Sample from a Dirichlet D times for the document-specific mixing probabilities. 
        # Draw βk independently for k = 1, . . . , K from Dirichlet(η).
        beta_cprobs = np.random.dirichlet([eta]*D + m_k, 1)
        beta[v,:] = np.random.dirichlet(beta_cprobs, 1)
        # Dirichlet K times for the topic-specific term probabilities
        
    
    if s <= burn_in:
        next
    
    # else, collect the samples. 
        
    
# Use collected samples to approximate joint distributions.
